### ISSUE TITLE
MVP HTML

### ISSUE THREAD

**Issue by Mbogaert** [Mbogaert/group-project-two#1]
Design the handlebars HTML pages

* landing page with signup and signin - Emily
* dashboard to add dog and create new post and get matched results (edit dog and humans after MVP) - Emily 
* survey page filling out information about the dog - Mathew
* dashboard after that displays results/dog matches (can edit post here, after MVP) - Mathew
* single post page (add comments) - Mathew
* new post page - Mathew

**Comment by thaiemily** [comment]
![image](https://user-images.githubusercontent.com/48578995/105573618-13f19900-5d1c-11eb-989e-a8f74606645a.png)

**Comment by Mbogaert** [comment]
I'm going to close this because we have all the above pages built at least
