### ISSUE TITLE
Addon package Ideas

### ISSUE THREAD

**Issue by ghost** [Mbogaert/group-project-two#16]
We need to try and resolve this issue relatively quickly for project requirements.

**Comment by ghost** [comment]
ideas

google maps

emailjs

**Comment by Mbogaert** [comment]
something with images - Filestack.js
https://www.npmjs.com/package/filestack-js

**Comment by ghost** [comment]
> something with images - Filestack.js
> https://www.npmjs.com/package/filestack-js

We should run with this package for MVP.
